# Generated by Django 4.2.6 on 2023-10-10 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=250)),
                ('neighborhood', models.CharField(choices=[('bienczyce', 'Bieńczyce'), ('bronowice', 'Bronowice'), ('czyzyny', 'Czyżyny'), ('debniki', 'Dębniki'), ('grzegorzki', 'Grzegórzki'), ('krowodrza', 'Krowodrza'), ('lagiewniki_Borek', 'Łagiewniki–Borek Fałęcki'), ('mistrzejowice', 'Mistrzejowice'), ('nh', 'Nowa Huta'), ('podgorze', 'Podgórze'), ('podgorze_duchackie', 'Podgórze Duchackie'), ('pradnik_bialy', 'Prądnik Biały'), ('pradnik_czerwony', 'Prądnik Czerwony'), ('prokocim', 'Bieżanów-Prokocim'), ('stare_miasto', 'Stare Miasto'), ('swoszowice', 'Swoszowice'), ('wzgorza_krzeslawickie', 'Wzgórza Krzesławickie'), ('zwierzyniec', 'Zwierzyniec')], max_length=21)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('date', models.DateField(auto_now=True)),
                ('lost', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
