# Generated by Django 4.2.6 on 2023-10-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_eventmodel_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event',
            field=models.TextField(max_length=250),
        ),
    ]
