# Generated by Django 4.2.6 on 2023-10-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_eventmodel_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='found',
            field=models.BooleanField(default=False),
        ),
    ]
