# Generated by Django 4.2.6 on 2023-10-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_alter_eventmodel_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='lost',
            field=models.BooleanField(help_text='This is the description for your_field.'),
        ),
    ]
