# Generated by Django 4.2.6 on 2023-10-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_alter_eventmodel_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='title',
            field=models.CharField(default="I've lost my pet", max_length=50),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='found',
            field=models.BooleanField(default=False, help_text='Mark this field if your pet was FOUND'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='lost',
            field=models.BooleanField(help_text='Mark this field if your pet is LOST'),
        ),
    ]
