# Generated by Django 4.2.6 on 2023-10-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_eventmodel_title_alter_eventmodel_found_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='found',
            field=models.BooleanField(default=False, help_text=' (Mark this field if your pet was FOUND)'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='lost',
            field=models.BooleanField(help_text=' (Mark this field if your pet is LOST)'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='neighborhood',
            field=models.CharField(choices=[('bienczyce', 'Bieńczyce'), ('prokocim', 'Bieżanów-Prokocim'), ('bronowice', 'Bronowice'), ('czyzyny', 'Czyżyny'), ('debniki', 'Dębniki'), ('grzegorzki', 'Grzegórzki'), ('krowodrza', 'Krowodrza'), ('lagiewniki_Borek', 'Łagiewniki–Borek Fałęcki'), ('mistrzejowice', 'Mistrzejowice'), ('nowahuta', 'Nowa Huta'), ('podgorze', 'Podgórze'), ('podgorze_duchackie', 'Podgórze Duchackie'), ('pradnik_bialy', 'Prądnik Biały'), ('pradnik_czerwony', 'Prądnik Czerwony'), ('stare_miasto', 'Stare Miasto'), ('swoszowice', 'Swoszowice'), ('wzgorza_krzeslawickie', 'Wzgórza Krzesławickie'), ('zwierzyniec', 'Zwierzyniec')], help_text=' (The last time the pet was seen.)', max_length=25),
        ),
    ]
