# Generated by Django 4.2.6 on 2023-10-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_alter_eventmodel_found_alter_eventmodel_lost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
