# Generated by Django 4.2.6 on 2023-10-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_eventmodel_age_eventmodel_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='eyesColor',
            field=models.CharField(choices=[('Yellow/Golden', 'Yellow/Golden'), ('Green', 'Green'), ('Blue', 'Blue'), ('Copper/amber', 'Copper/Amber'), ('Odd-Eyed', 'Odd-Eyed (2 different colors each)'), ('Mixed Colors', 'Mixed Colors')], default='chose one option', max_length=35),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'female')], default='chose one option', max_length=6),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='neighborhood',
            field=models.CharField(choices=[('Bieńczyce', 'Bieńczyce'), ('Bieżanów-Prokocim', 'Bieżanów-Prokocim'), ('Bronowice', 'Bronowice'), ('Czyżyny', 'Czyżyny'), ('Dębniki', 'Dębniki'), ('Grzegórzki', 'Grzegórzki'), ('Krowodrza', 'Krowodrza'), ('Łagiewniki–Borek Fałęcki', 'Łagiewniki–Borek Fałęcki'), ('Mistrzejowice', 'Mistrzejowice'), ('Nowa Huta', 'Nowa Huta'), ('Podgórze', 'Podgórze'), ('Podgórze Duchackie', 'Podgórze Duchackie'), ('Prądnik Biały', 'Prądnik Biały'), ('Prądnik Czerwony', 'Prądnik Czerwony'), ('Stare Miasto', 'Stare Miasto'), ('Swoszowice', 'Swoszowice'), ('Wzgórza Krzesławickie', 'Wzgórza Krzesławickie'), ('Zwierzyniec', 'Zwierzyniec')], help_text='(The last time the pet was seen.)', max_length=25),
        ),
    ]
