# Generated by Django 4.2.6 on 2023-10-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_alter_eventmodel_eyescolor_alter_eventmodel_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='age',
            field=models.CharField(choices=[('baby (until 1 year old)', 'baby (until 1 year old)'), ('adult (until 10 years old)', 'adult (until 10 years old)'), ('senior (from 10 years old)', 'senior (from 10 years old)')], default='chose one option', max_length=26),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='furColor',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Orange', 'Orange'), ('Grey', 'Grey'), ('2 different colors', '2 different colors'), ('3 different colors', '3 different colors')], default='chose one option', help_text='(The dominant one.)', max_length=18),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='chose one option', max_length=6),
        ),
    ]
