# Generated by Django 4.2.6 on 2023-10-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_alter_eventmodel_age_alter_eventmodel_furcolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='age',
            field=models.CharField(choices=[('baby (until 1 year old)', 'baby (until 1 year old)'), ('adult (until 10 years old)', 'adult (until 10 years old)'), ('senior (from 10 years old)', 'senior (from 10 years old)')], max_length=26),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='eyesColor',
            field=models.CharField(choices=[('Yellow/Golden', 'Yellow/Golden'), ('Green', 'Green'), ('Blue', 'Blue'), ('Copper/amber', 'Copper/Amber'), ('Odd-Eyed', 'Odd-Eyed (2 different colors each)'), ('Mixed Colors', 'Mixed Colors')], max_length=35),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='furColor',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Orange', 'Orange'), ('Grey', 'Grey'), ('2 different colors', '2 different colors'), ('3 different colors', '3 different colors')], help_text='(The dominant one.)', max_length=18),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
