# Generated by Django 4.2.6 on 2023-11-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0016_alter_eventmodel_age_alter_eventmodel_eyescolor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='contact',
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='age',
            field=models.CharField(blank=True, choices=[('baby (until 1 year old)', 'baby (until 1 year old)'), ('adult (until 10 years old)', 'adult (until 10 years old)'), ('senior (from 10 years old)', 'senior (from 10 years old)')], max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='eyesColor',
            field=models.CharField(blank=True, choices=[('Yellow/Golden', 'Yellow/Golden'), ('Green', 'Green'), ('Blue', 'Blue'), ('Copper/amber', 'Copper/Amber'), ('Odd-Eyed', 'Odd-Eyed (2 different colors each)'), ('Mixed Colors', 'Mixed Colors')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
    ]
