# Generated by Django 4.2.6 on 2023-11-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0017_remove_eventmodel_contact_alter_eventmodel_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='contact',
            field=models.EmailField(blank=True, default='youremail@example.com', help_text='(This info will be displayed only in the Pet Searcher, if the system finds potential candidates.)', max_length=254),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='lost',
            field=models.BooleanField(help_text='(Mark this field if YOUR pet is LOST. If you found a pet DO NOT mark it.)'),
        ),
    ]
