# Generated by Django 4.2.6 on 2023-11-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0018_eventmodel_contact_alter_eventmodel_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='type',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('other', 'other')], default='cat', max_length=5),
        ),
    ]
