# Generated by Django 4.2.6 on 2023-11-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0019_eventmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='type',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('other', 'other')], max_length=5),
        ),
    ]
