# Generated by Django 4.2.6 on 2023-11-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0020_alter_eventmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='age',
            field=models.CharField(blank=True, choices=[('dziecko (do 1 roku życia)', 'dziecko (do 1 roku życia)'), ('dorosły (do 10 roku życia)', 'dorosły (do 10 roku życia)'), ('seniorzy (od 10 lat)', 'seniorzy (od 10 lat)')], max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='contact',
            field=models.EmailField(blank=True, default='youremail@example.com', help_text='(Informacja ta wyświetli się tylko w Wyszukiwarce Zwierzaków, jeśli system znajdzie potencjalnych kandydatów.)', max_length=254),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='eyesColor',
            field=models.CharField(blank=True, choices=[('Żółty/złoty', 'Żółty/złoty'), ('Zielony', 'Zielony'), ('Niebieski', 'Niebieski'), ('Miedź/bursztyn', 'Miedź/bursztyn'), ('Dziwne oczy', 'Dziwne oczy'), ('Mieszane kolory', 'Mieszane kolory')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='found',
            field=models.BooleanField(default=False, help_text='(Zaznacz to pole, jeśli ZNALEZIONO Twoje zwierzę)'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='furColor',
            field=models.CharField(choices=[('Czarny', 'Czarny'), ('Biały', 'Biały'), ('Pomarańczy', 'Pomarańczy'), ('Szary', 'Szary'), ('Dwa różne kolory', 'Dwa różne kolory'), ('Try różne kolory', 'Try różne kolory')], help_text='(Dominujący)', max_length=18),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Mężczyzna', 'Mężczyzna'), ('Kobieta', 'Kobieta')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='lost',
            field=models.BooleanField(help_text='(Zaznacz to pole, jeśli TWÓJ zwierzak zaginął. Jeśli znalazłeś zwierzaka, NIE zaznaczaj go.)'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='neighborhood',
            field=models.CharField(choices=[('Bieńczyce', 'Bieńczyce'), ('Bieżanów-Prokocim', 'Bieżanów-Prokocim'), ('Bronowice', 'Bronowice'), ('Czyżyny', 'Czyżyny'), ('Dębniki', 'Dębniki'), ('Grzegórzki', 'Grzegórzki'), ('Krowodrza', 'Krowodrza'), ('Łagiewniki–Borek Fałęcki', 'Łagiewniki–Borek Fałęcki'), ('Mistrzejowice', 'Mistrzejowice'), ('Nowa Huta', 'Nowa Huta'), ('Podgórze', 'Podgórze'), ('Podgórze Duchackie', 'Podgórze Duchackie'), ('Prądnik Biały', 'Prądnik Biały'), ('Prądnik Czerwony', 'Prądnik Czerwony'), ('Stare Miasto', 'Stare Miasto'), ('Swoszowice', 'Swoszowice'), ('Wzgórza Krzesławickie', 'Wzgórza Krzesławickie'), ('Zwierzyniec', 'Zwierzyniec')], help_text='(Ostatni raz widziano zwierzaka.)', max_length=25),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='type',
            field=models.CharField(choices=[('kot', 'kot'), ('pies', 'pies'), ('inny', 'inny')], max_length=5),
        ),
    ]
